---
# The variables file used by the playbooks in the mac group.

homebrew_packages:
  - name: chromedriver
  - name: git
  - name: git-secrets
  - name: gnuplot
  - name: go
  - name: guetzli
  - {name: heroku, state: absent, install_options: force}
  - name: jq
  - name: lv
  - name: mecab
  - name: mongodb
  - name: mysql
  - name: nmap
  - {name: node, state: absent, install_options: force}
  - name: nodebrew
  - name: octave
  - name: openssl
  - name: phantomjs
  - name: pkg-config
  - name: postgresql
  - name: pyenv
  - name: rbenv
  - name: ruby-build
  - name: sqlite
  - name: travis
  - name: tree
  - name: vagrant-completion
  - name: wget

pyenv:
  default_python: 3.6.3
  pythons:
    - version: 3.6.3

pip_packages:
  - name: ansible
  - name: awscli
  - name: beautifulsoup4
  - name: boto
  - name: boto3
  - name: django
  - name: jinja2
  - name: numpy
  - name: pymongo
  - name: robobrowser
  - name: scrapy
  - name: selenium

rbenv:
  default_ruby: 2.4.1
  rubies:
    - version: 2.2.3
    - version: 2.3.0
    - version: 2.3.1
    - version: 2.4.1

nodebrew:
  default_node: v9.4.0
  nodes:
    - version: v6.10.3
    - version: v9.4.0

npm_packages:
  - name: npm
  - name: typescript
