# The variables file used by the playbooks in the mac group.

homebrew_taps:
  - tap: sanemat/font
  - tap: kyoshidajp/ghkw

homebrew_packages:
  - name: autojump
  - name: bash-completion
  - name: fish
  - name: iproute2mac
  - name: jq
  - { name: jsonlint, state: absent, install_options: force }
  - name: nmap
  - { name: node, state: absent, install_options: force }
  - name: nodebrew
  - name: openssl
  - name: pkg-config
  - name: tmux
  - name: tree
  - name: wireshark
  - name: wget
  - name: zsh
  - name: font-hackgen
  - name: font-hackgen-nerd



pip_packages:
  - name: ansible
  - name: awscli
  - name: aws-shell
  - { name: aws-sam-cli, state: absent }
  - name: boto
  - name: boto3
  - { name: django, state: absent }
  - name: pip
  - name: powerline-status

homebrew_cask_packages:
  # - name: google-chrome
  # - name: docker
  # - name: slack
  - name: remote-desktop-manager
  - name: karabiner-elements
  - name: visual-studio-code



rbenv:
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1

nodebrew:
  default_node: v14
  nodes:
    - version: v12

npm_packages:
  - name: aws-cdk
  - name: aws-sam-local
  - name: cfn-lint
  - name: jsonlint
  - name: npm@lts
  - name: npm-check-updates
  - name: eslint
  - name: eslint-config-prettier
  - name: eslint-plugin-prettier
  - name: swagger
  - name: textlint
  - name: textlint-rule-max-ten
  - name: textlint-rule-no-mix-dearu-desumasu
  - name: textlint-rule-spellcheck-tech-word
  - { name: typescript, state: absent }
