# The variables file used by the playbooks in the mac group.

homebrew_taps:
  - tap: caskroom/cask
  - tap: kyoshidajp/ghkw

homebrew_packages:
  - name: chromedriver
  - name: editorconfig
  - name: ghkw
  - name: git
  - name: git-secrets
  - name: gnuplot
  - name: go
  - {name: guetzli, state: absent, install_options: force}
  - {name: heroku, state: absent, install_options: force}
  - name: jq
  - {name: kibana, state: absent, install_options: force}
  - {name: kibana@5.6, state: absent, install_options: force}
  - {name: kibana@4.4, state: absent, install_options: force}
  - name: lv
  - name: mecab
  - name: mongodb
  - name: mysql
  - name: nmap
  - {name: node, state: absent, install_options: force}
  - name: nodebrew
  - name: octave
  - name: openssl
  - name: phantomjs
  - name: pkg-config
  - name: postgresql
  - name: pyenv
  - name: rbenv
  - name: ruby-build
  - name: screen
  - name: sqlite
  - name: travis
  - name: tree
  - name: vagrant-completion
  - name: vim
  - name: wget

pyenv:
  default_python: 3.6.3
  pythons:
    - version: 3.6.3

pip_packages:
  - name: ansible
  - name: awscli
  - { name: beautifulsoup4, state: absent }
  - name: boto
  - name: boto3
  - { name: django, state: absent }
  - name: jinja2
  - name: localstack
  - { name: numpy, state: absent }
  - { name: pymongo, state: absent }
  - { name: robobrowser, state: absent }
  - { name: scrapy, state: absent }
  - { name: selenium, state: absent }

homebrew_cask_packages:
  - name: docker-toolbox

rbenv:
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1

nodebrew:
  default_node: v9.4.0
  nodes:
    - version: v6.10.3
    - version: v9.4.0

npm_packages:
  - name: aws-sam-local
  - name: npm
  - { name: typescript, state: absent }
