# The variables file used by the playbooks in the mac group.

homebrew_taps:
  - tap: caskroom/cask
  - tap: kyoshidajp/ghkw

homebrew_packages:
  - { name: ansible, state: absent, install_options: force }
  - name: autojump
  - name: chromedriver
  - name: editorconfig
  - name: emacs
  - name: fish
  - name: fzf
  - name: ghkw
  - name: git
  - name: git-secrets
  - name: gnuplot
  - name: go
  - name: graphviz
  - { name: guetzli, state: absent, install_options: force }
  - { name: heroku, state: absent, install_options: force }
  - name: jq
  - { name: kibana, state: absent, install_options: force }
  - { name: kibana@5.6, state: absent, install_options: force }
  - { name: kibana@4.4, state: absent, install_options: force }
  - name: less
  - name: lv
  - name: mecab
  - name: mongodb
  - name: mysql
  - name: nmap
  - { name: node, state: absent, install_options: force }
  - name: nodebrew
  - name: octave
  - name: openssl
  - name: phantomjs
  - name: plantuml
  - name: pkg-config
  - name: postgresql
  - { name: pyenv, state: absent, installoptions: force }
  - name: python
  - name: rbenv
  - name: ruby-build
  - name: screen
  - { name: sphinx, state: absent, installoptions: force }
  - name: sqlite
  - name: terraform
  - name: tig
  - name: tmux
  - name: travis
  - name: tree
  - name: vagrant-completion
  - name: vim
  - name: wget
  - name: zsh

pip_packages:
  - name: ansible
  - name: awscli
  - name: aws-sam-cli
  - { name: beautifulsoup4, state: absent }
  - name: boto
  - name: boto3
  - { name: django, state: absent }
  - name: jinja2
  - name: json2yaml
  - { name: localstack, state: absent }
  - { name: numpy, state: absent }
  - name: pip
  - { name: pymongo, state: absent }
  - { name: robobrowser, state: absent }
  - { name: scrapy, state: absent }
  - { name: selenium, state: absent }
  - name: sphinx

homebrew_cask_packages:
  - name: docker-toolbox

rbenv:
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1

nodebrew:
  default_node: v6.10.3
  nodes:
    - version: v6.10.3
    - version: V8.10.0
    - version: v9.4.0

npm_packages:
  - { name: aws-sam-local, state: absent }
  - name: npm@lts
  - name: npm-check-updates
  - name: textlint
  - name: textlint-rule-max-ten
  - name: textlint-rule-no-mix-dearu-desumasu
  - name: textlint-rule-spellcheck-tech-word
  - { name: typescript, state: absent }
