# The variables file used by the playbooks in the mac group.

homebrew_taps:
  - tap: homebrew/cask
  - tap: kyoshidajp/ghkw

homebrew_packages:
  - name: autojump
  - name: bash-completion
  - name: fish
  - name: iproute2mac
  - name: jq
  - { name: jsonlint, state: absent, install_options: force }
  - name: nmap
  - { name: node, state: absent, install_options: force }
  - name: nodebrew
  - name: openssl
  - name: pkg-config
  - name: python
  - name: screen
  - name: tmux
  - name: tree
  - name: vagrant-completion
  - { name: vim, install_options: without-python }
  - name: wireshark
  - name: wget
  - name: zsh


pip_packages:
  - name: ansible
  - name: awscli
  - name: aws-shell
  - { name: aws-sam-cli, state: absent }
  - name: boto
  - name: boto3
  - { name: django, state: absent }
  - name: pip
  - name: powerline-status

homebrew_cask_packages:
  # - name: google-chrome
  - name: docker
  - name: slack



rbenv:
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1

nodebrew:
  default_node: v8.10.0
  nodes:
    - version: v6.10.3
    - version: v8.10.0
    - version: v9.4.0

npm_packages:
  - name: aws-cdk
  - name: aws-sam-local
  - name: cfn-lint
  - name: jsonlint
  - name: npm@lts
  - name: npm-check-updates
  - name: swagger
  - name: textlint
  - name: textlint-rule-max-ten
  - name: textlint-rule-no-mix-dearu-desumasu
  - name: textlint-rule-spellcheck-tech-word
  - { name: typescript, state: absent }
