---
- name: install ricty font 
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("latest") }}'
    install_options: '{{ item.install_options | default() | join(",") if item.install_options is not string else item.install_options }}'
  with_items:
    - { name: "ricty", install_options: with-powerline }

- name: copy builded ricty font
  copy:
    src: '/usr/local/opt/ricty/share/fonts/{{ item }}'
    dest: ~/Library/Fonts/
    remote_src: yes
    force: yes
  with_items:
    - Ricty Bold for Powerline.ttf
    - Ricty-Bold.ttf
    - Ricty Discord Bold for Powerline.ttf
    - Ricty-Regular.ttf
    - Ricty Discord Regular for Powerline.ttf	
    - RictyDiscord-Bold.ttf
    - Ricty Regular for Powerline.ttf
    - RictyDiscord-Regular.ttf

- name: build fonts chash
  command: "fc-cache -vf"