---
- name: homebrew update
  homebrew:
    update_homebrew: yes

- name: homebrew packages install
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    install_options: '{{ item.install_options | default() | join(",") if item.install_options is not string else item.install_options }}'
  with_items: '{{ homebrew_packages }}'
